- op: replace
  path: /metadata/name
  value: argocd-dev-application-controller
- op: replace
  path: /roleRef/name
  value: argocd-dev-application-controller
- op: replace
  path: /subjects/0/name
  value: argocd-dev-application-controller